function row = resultRow(baseName, res)
    if ~isfield(res,'numMismatch'), res.numMismatch = []; end
    if ~isfield(res,'shift'),       res.shift       = []; end
    if ~isfield(res,'areaRatio'),   res.areaRatio   = []; end
    row = table( string(baseName), ...
                 double(res.numMismatch), ...
                 double(res.shift), ...
                 double(res.areaRatio), ...
                 string(timestamp()), ...
                 'VariableNames', {'Fajl','Nepoklapanja','Pomeraj','OdnosPovrsina','Vreme'});
end
